org: jiro0403
app: klima-aws-scheduled-cron-app
service: klima-aws-scheduled-cron-app
variablesResolutionMode: 20210326

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every xx:00 every day
      - schedule: cron(0 * * * ? *)
    environment:
      PRIVATE_KEY: ${ssm:/klima/private-key}
      SWAP_PERCENT: ${ssm:/klima/swap-percent}
